// Generated by scripts/generate-frontend-application-locales.mjs. Edit the full locale catalog, then regenerate.
export default {
  "nav": {
    "sections": "板块",
    "latest": "最新",
    "top": "热门",
    "new": "新主题",
    "activity": "动态",
    "search": "搜索",
    "tags": "标签",
    "badges": "徽章",
    "members": "成员",
    "staff": "管理团队",
    "staffWorkspace": "站务工作台",
    "statistics": "统计",
    "help": "帮助",
    "watching": "关注主题",
    "watchedTags": "关注标签",
    "watchedTagTopics": "标签主题",
    "following": "关注用户",
    "bookmarks": "书签",
    "unread": "未读",
    "assigned": "指派",
    "moderationApprovals": "待审核",
    "messages": "私信",
    "drafts": "草稿",
    "preferences": "偏好",
    "blocks": "拉黑",
    "ignores": "忽略",
    "muted": "静音",
    "products": "商品",
    "compare": "对比",
    "recentlyViewed": "最近浏览",
    "orders": "我的订单",
    "wishlist": "心愿单",
    "shippingAddresses": "收货地址",
    "wallet": "商店余额",
    "giftCards": "礼品卡",
    "stockAlerts": "到货通知",
    "priceAlerts": "降价提醒",
    "availabilityAlerts": "上架通知",
    "storePreferences": "商城通知",
    "cart": "购物车",
    "personal": "我的",
    "forum": "论坛",
    "store": "商城"
  },
  "portal": {
    "userCenter": "用户中心",
    "profile": "个人资料",
    "forumPreferences": "论坛偏好",
    "brand": "McWeb",
    "backToWebsite": "返回官网",
    "serverStatus": "服务器状态",
    "serverStatusOnline": "在线",
    "serverStatusOffline": "离线",
    "serverStatusMaintenance": "维护中",
    "serverAnomalyHint": "有服务器需要关注",
    "online": "在线"
  },
  "breadcrumb": {
    "home": "首页",
    "account": "账户",
    "forum": "论坛",
    "store": "商城",
    "label": "面包屑导航"
  },
  "accountCenter": {
    "title": "个人中心",
    "overview": "概览",
    "subtitle": "查看你的身份、安全状态和需要处理的事项。",
    "open": "打开",
    "openItem": "打开{item}",
    "actions": {
      "profile": "编辑个人资料",
      "password": "修改密码",
      "security": "安全设置",
      "minecraft": "Minecraft 账户"
    },
    "status": {
      "verified": "已验证",
      "unverified": "未验证",
      "enabled": "已启用",
      "disabled": "未启用"
    },
    "identity": {
      "title": "账户信息",
      "username": "用户名",
      "language": "界面语言",
      "joinedAt": "加入时间"
    },
    "security": {
      "title": "安全状态",
      "email": "邮箱",
      "twoFactor": "两步验证",
      "sessions": "活跃会话",
      "review": "查看安全设置"
    },
    "activity": {
      "title": "需要你处理",
      "notifications": "未读通知",
      "messages": "未读私信",
      "drafts": "已保存主题草稿",
      "open": "查看详情"
    },
    "minecraft": {
      "title": "主 Minecraft 身份",
      "unbound": "尚未绑定 Minecraft 身份。",
      "bind": "绑定账户",
      "manage": "管理绑定账户"
    },
    "groups": {
      "community": "社区动态",
      "content": "内容与沟通",
      "account": "账户与隐私",
      "moreCommunity": "更多社区工具",
      "privacy": "社区隐私"
    },
    "items": {
      "newTopics": {
        "title": "新主题",
        "description": "查看你上次访问后的主题。"
      },
      "unread": {
        "title": "未读",
        "description": "继续阅读尚未看完的主题。"
      },
      "watching": {
        "title": "关注主题",
        "description": "管理你关注的主题。"
      },
      "following": {
        "title": "关注用户",
        "description": "查看你关注的成员动态。"
      },
      "watchedTags": {
        "title": "关注标签",
        "description": "管理你关注的标签。"
      },
      "watchedTagTopics": {
        "title": "标签主题",
        "description": "浏览关注标签下的主题。"
      },
      "bookmarks": {
        "title": "书签",
        "description": "回到已保存的帖子和主题。"
      },
      "messages": {
        "title": "私信",
        "description": "查看和管理你的私信会话。"
      },
      "drafts": {
        "title": "草稿",
        "description": "继续编辑已保存的主题和回复。"
      },
      "preferences": {
        "title": "社区偏好",
        "description": "调整社区在你账户上的显示和行为。"
      },
      "blocks": {
        "title": "拉黑用户",
        "description": "查看已拉黑的成员。"
      },
      "ignores": {
        "title": "忽略用户",
        "description": "查看已隐藏其内容的成员。"
      },
      "muted": {
        "title": "静音内容",
        "description": "管理静音的主题和板块。"
      },
      "security": {
        "title": "账户安全",
        "description": "管理邮箱、双重验证和账户关闭。"
      },
      "sessions": {
        "title": "登录会话",
        "description": "查看并撤销已登录的设备。"
      },
      "dataExports": {
        "title": "数据导出",
        "description": "申请并下载你的数据副本。"
      },
      "minecraft": {
        "title": "Minecraft 账户",
        "description": "绑定并管理你的 Minecraft 身份。"
      }
    }
  },
  "accountNotifications": {
    "title": "通知",
    "markAllRead": "全部已读",
    "dismissAlerts": "清除提醒",
    "alert": "提醒",
    "all": "全部",
    "allMessages": "全部消息",
    "unread": "未读",
    "categoryFilter": "分类：",
    "readFilter": "阅读状态：",
    "typeFilter": "通知类型：",
    "timeFilter": "时间筛选：",
    "quickFilter": "快捷筛选：",
    "unreadCount": "{count} 未读",
    "activeFilters": "已选筛选：",
    "removeFilter": "移除此筛选",
    "clearAll": "清除全部",
    "collapse": "收起",
    "expand": "展开",
    "view": "查看",
    "markRead": "已读",
    "delete": "删除",
    "deleteTitle": "删除通知",
    "deleteConfirm": "确定删除这条通知吗？此操作无法撤销。",
    "empty": "暂无通知。"
  },
  "auth": {
    "passwordReset": {
      "title": "重置密码",
      "subtitle": "输入注册邮箱以接收重置链接",
      "email": "邮箱",
      "submit": "发送重置链接",
      "backToSignIn": "返回登录",
      "editTitle": "设置新密码",
      "editSubtitle": "请输入新密码",
      "newPassword": "新密码",
      "confirmPassword": "确认密码",
      "updatePassword": "更新密码",
      "failed": "重置失败",
      "sendFailed": "无法发送",
      "updateFailed": "无法更新密码"
    },
    "signIn": {
      "title": "登录",
      "subtitle": "访问你的 Mcweb 账户",
      "failed": "登录失败",
      "email": "邮箱",
      "password": "密码",
      "totp": "两步验证码（如已启用）",
      "rememberMe": "记住我",
      "createAccount": "创建账户",
      "lostTwoFactor": "无法使用两步验证？"
    },
    "twoFactor": {
      "title": "两步验证",
      "subtitle": "输入验证器生成的验证码或账户恢复码",
      "code": "验证码或恢复码",
      "verify": "继续登录",
      "failed": "验证失败",
      "backToSignIn": "返回登录",
      "recover": "无法使用验证器？"
    },
    "register": {
      "title": "创建账户",
      "subtitle": "加入 Mcweb 社区",
      "failed": "注册失败",
      "email": "邮箱",
      "username": "用户名",
      "displayName": "显示名称",
      "password": "密码",
      "locale": "界面语言",
      "timeZone": "时区",
      "hasAccount": "已有账户？登录"
    }
  },
  "identity": {
    "profile": {
      "title": "编辑个人资料",
      "subtitle": "维护公开显示名称与应用界面语言",
      "accountIdentity": "账户身份",
      "editableDetails": "资料偏好",
      "username": "用户名",
      "email": "邮箱",
      "readOnlyHint": "用户名和邮箱分别由专用账户流程管理。",
      "displayName": "显示名称",
      "displayNameHint": "可选，最多 64 个字符，不允许控制字符。",
      "displayNamePlaceholder": "希望别人看到的名称",
      "language": "应用界面语言",
      "languageHint": "保存后会同时更新当前会话和之后访问时的语言。",
      "save": "保存个人资料"
    },
    "password": {
      "title": "修改密码",
      "subtitle": "确认本人身份后更换登录密码",
      "formTitle": "密码与身份验证",
      "sessionNotice": "修改成功后，本设备保持登录，其他登录会话会全部退出。",
      "currentPassword": "当前密码",
      "newPassword": "新密码",
      "confirmPassword": "确认新密码",
      "passwordHint": "至少 6 个字符，且不要继续使用当前密码。",
      "twoFactorCode": "两步验证码或恢复码",
      "twoFactorHint": "输入当前验证器代码，或一个尚未使用的恢复码。",
      "twoFactorPlaceholder": "一次性验证码",
      "submit": "修改密码",
      "cancel": "返回安全设置"
    },
    "sessions": {
      "title": "活跃会话",
      "subtitle": "管理你的登录设备",
      "colIp": "IP",
      "colDevice": "设备",
      "colLastActive": "最后活跃",
      "current": "当前",
      "revoke": "撤销"
    },
    "security": {
      "title": "账户安全",
      "subtitle": "管理邮箱、两步验证、恢复方式和账户状态",
      "changePassword": "修改密码",
      "emailTitle": "邮箱验证",
      "emailHint": "敏感变更需要重新验证密码和两步验证码。",
      "verified": "已验证",
      "unverified": "未验证",
      "changeEmailTitle": "修改邮箱",
      "changeEmailHint": "确认新邮箱前，当前邮箱仍可正常登录。",
      "newEmail": "新邮箱",
      "changeEmail": "向新邮箱发送确认邮件",
      "pendingEmailTitle": "邮箱修改等待确认",
      "pendingEmailDescription": "请前往 {email} 的收件箱确认修改；当前邮箱已收到取消链接。",
      "pendingEmailExpires": "确认链接将于 {at} 失效。",
      "totpTitle": "两步验证",
      "totpHint": "使用验证器应用生成一次性验证码。",
      "enabled": "已启用",
      "disabled": "未启用",
      "requiredNotice": "管理员要求你启用两步验证后才能继续使用站点。",
      "scanQr": "使用验证器应用扫描二维码，或手动输入密钥。",
      "startTotp": "开始设置两步验证",
      "confirmTotpHint": "请重新输入密码以保护绑定流程。启用两步验证后，其他设备会全部退出登录。",
      "confirmTotp": "确认并启用",
      "disableTotp": "关闭两步验证",
      "disableTotpHint": "关闭后，现有验证器密钥和恢复码会立即失效。",
      "recoveryCodesTitle": "恢复码",
      "recoveryCodesRemaining": "剩余恢复码：{count} 个",
      "recoveryCodesOneTimeTitle": "立即保存恢复码",
      "recoveryCodesOneTimeHint": "这些恢复码只显示一次。每个恢复码只能使用一次，请保存到安全位置。",
      "copyRecoveryCodes": "复制恢复码",
      "downloadRecoveryCodes": "下载文本文件",
      "recoveryCodesCopied": "恢复码已复制。",
      "recoveryCodesCopyFailed": "无法自动复制，请手动选择并保存。",
      "recoveryCodesDownloaded": "恢复码文件已下载。",
      "recoveryCodesAcknowledgement": "我已将恢复码保存到安全位置，并了解离开页面后不会再次显示。",
      "finishRecoveryCodes": "我已安全保存",
      "regenerateRecoveryCodes": "重新生成恢复码",
      "regenerateRecoveryCodesHint": "重新生成会立即撤销全部旧恢复码，需要密码和当前验证码。",
      "closeAccountTitle": "关闭账户",
      "closeAccountHint": "这是不可逆的自助关闭流程。提交前请确认下面的数据处理结果。",
      "closeAccountProfile": "邮箱、用户名、显示名称、简介、头像和安全凭据会被移除或匿名化。",
      "closeAccountContent": "已发布内容会保留，并改为稳定的匿名作者，避免破坏讨论结构。",
      "closeAccountRecords": "订单、付款、退款、审核和审计记录会按法定及产品保留要求继续保存。",
      "closeAccountSessions": "所有登录会话和 API 密钥会立即撤销。",
      "closeAccountConfirmation": "输入 DELETE 确认关闭",
      "closeAccountConfirmationPlaceholder": "DELETE",
      "closeAccountReason": "关闭原因（可选）",
      "closeAccountReasonPlaceholder": "帮助我们理解你的决定，请勿填写密码或其他敏感信息。",
      "closeAccountContentChoice": "选择如何处理你发布的社区内容",
      "closeAccountAnonymize": "以稳定匿名作者保留讨论",
      "closeAccountAnonymizeHint": "个人身份会被移除，已发布讨论继续保持可读和结构完整。",
      "closeAccountDeleteContent": "申请删除本人发布的社区内容",
      "closeAccountDeleteContentHint": "符合条件的主题、回复和私信会被移除；受保护证据与治理记录仍会保留。",
      "closeAccountLegalHoldHint": "未结举报或 legal hold 可以阻止删除。系统会记录最终结果，但不会向普通用户暴露受保护证据。",
      "closeAccount": "永久关闭账户"
    },
    "dataExports": {
      "title": "我的数据导出",
      "subtitle": "创建并管理 McWeb 账户数据的私密归档",
      "request": "申请新导出",
      "privacyTitle": "私密的限时下载",
      "privacyDescription": "导出会在 {hours} 小时后过期，每 24 小时最多申请 {limit} 次；撤销后会移除下载文件。",
      "emptyTitle": "还没有数据导出",
      "emptyDescription": "申请后，系统会在后台生成 ZIP 归档。",
      "history": "数据导出记录",
      "exportLabel": "账户数据归档",
      "requestedAt": "申请时间",
      "expiresAt": "过期时间",
      "attempts": "生成次数",
      "totalRecords": "共包含 {count} 条记录",
      "recordCount": "{count} 条记录",
      "moduleSummary": "各模块包含的记录",
      "olderHistory": "查看更早的导出",
      "download": "下载 ZIP",
      "retry": "重试",
      "revoke": "撤销",
      "revokeConfirm": "确定撤销此导出并移除下载文件吗？",
      "failedDescription": "生成失败，内部错误细节不会暴露；可以安全重试。",
      "backToSecurity": "返回账户安全",
      "modules": {
        "identityProfile": "账户资料",
        "identityNotifications": "通知",
        "communityContent": "社区内容",
        "communityUploads": "上传文件",
        "commerceAccount": "商城账户数据"
      },
      "status": {
        "queued": "等待中",
        "running": "生成中",
        "completed": "可下载",
        "failed": "失败",
        "revoked": "已撤销",
        "expired": "已过期"
      }
    },
    "totpRecovery": {
      "requestTitle": "恢复两步验证访问",
      "requestSubtitle": "通过已验证邮箱申请一次性恢复链接",
      "securityTitle": "不会泄露账户状态",
      "securityHint": "无论邮箱是否存在，页面都会显示相同结果。恢复链接有效期为 30 分钟。",
      "send": "发送恢复链接",
      "completeTitle": "重置两步验证",
      "completeSubtitle": "验证账户密码后移除旧验证器和恢复码",
      "failedTitle": "无法完成恢复",
      "sessionWarningTitle": "安全提醒",
      "sessionWarning": "成功后，所有现有登录会话都会被撤销，你需要重新登录并设置新的两步验证。",
      "reset": "重置两步验证并撤销会话"
    },
    "resendVerification": {
      "title": "重发验证邮件",
      "subtitle": "输入注册邮箱以重新接收验证链接",
      "hint": "如果邮箱已验证或不存在，我们不会透露账户状态，但也不会发送邮件。",
      "submit": "发送验证邮件"
    }
  },
  "minecraft": {
    "title": "Minecraft",
    "link": {
      "title": "绑定 Minecraft 账户",
      "subtitle": "在游戏内执行 /website link，然后输入验证码",
      "code": "验证码",
      "submit": "绑定账户",
      "notLinked": "尚未绑定 Minecraft 账号。",
      "goLink": "前往绑定",
      "lastSeen": "最近游戏",
      "lastSeenAt": "最近游戏：{time}",
      "fullBody": "全身",
      "playerId": "玩家 ID：{id}",
      "boundAccountsTitle": "已绑定的 Minecraft 账号",
      "addAccountTitle": "继续绑定 Minecraft 账号",
      "primaryAccount": "主账号",
      "setPrimaryAccount": "设为主账号",
      "requestPrimaryAccount": "申请切换主账号",
      "primaryPolicyImmediate": "主账号切换会立即生效。",
      "primaryPolicyStaffApproval": "主账号切换需要工作人员审批，申请会在 {hours} 小时后过期。",
      "primaryPolicyAdministratorOnly": "只有获得授权的管理员可以切换主账号。",
      "primaryCooldownActive": "可在 {time} 后再次切换主账号。",
      "pendingPrimaryRequestTitle": "已有一项主账号切换申请等待处理",
      "pendingPrimaryRequestBody": "目标账号：{account}；申请将在 {time} 过期。",
      "cancelPrimaryRequest": "取消申请",
      "primaryRequestReason": "切换理由",
      "primaryRequestReasonHelp": "工作人员会在审批时查看这段说明。",
      "primaryRequestReasonPlaceholder": "请说明为什么要将这个账号设为主账号……",
      "skinCached": "皮肤已缓存到应用内",
      "skinCachePending": "等待生成本地皮肤缓存",
      "linkedAt": "绑定于 {time}",
      "unlinkAccount": "解除绑定",
      "unlinkAccountLabel": "解除 Minecraft 账号 {account} 的绑定",
      "unlinkTitle": "解除 Minecraft 账号绑定",
      "unlinkConfirmAction": "确认解除绑定",
      "unlinkWarningTitle": "此操作会从你的站内资料中移除该账号",
      "unlinkWarningBody": "继续前请核对所选账号，并确认你已了解后续影响。",
      "unlinkConsequencesTitle": "解除绑定后",
      "unlinkConsequenceAccess": "站内功能将不再把这个 Minecraft 身份视为你的已绑定账号。",
      "unlinkConsequencePrimary": "如果它是主账号，系统会自动将仍在绑定的最早账号设为主账号。",
      "unlinkConsequenceRequests": "所有涉及这个账号、尚未处理的主账号切换申请都会被取消。",
      "unlinkConsequenceRelink": "如需再次使用这个身份，你必须重新完成游戏内绑定流程。",
      "unlinkConfirmationLabel": "确认账号名称",
      "unlinkConfirmationHelp": "请输入 {account}，必须与当前账号名称完全一致。"
    }
  }
} as Record<string, unknown>
