// Generated by scripts/generate-frontend-application-locales.mjs. Edit the full locale catalog, then regenerate.
export default {
  "common": {
    "cancel": "取消",
    "confirm": "确定",
    "close": "关闭",
    "save": "保存",
    "signIn": "登录",
    "signOut": "退出登录",
    "signOutConfirmTitle": "确认退出登录？",
    "signOutConfirmDescription": "退出后，本设备上的当前会话将结束。",
    "refresh": "刷新",
    "register": "注册",
    "loading": "加载中…",
    "browse": "浏览",
    "back": "返回",
    "view": "查看",
    "preview": "预览",
    "edit": "编辑",
    "delete": "删除",
    "actions": "操作",
    "mine": "我的",
    "announcement": "公告",
    "closeAnnouncement": "关闭公告",
    "openMenu": "打开菜单",
    "navigation": "主导航",
    "skipToContent": "跳到主要内容",
    "toggleTheme": "切换主题",
    "notifications": "通知",
    "messages": "私信",
    "cart": "购物车",
    "applicationUnavailable": "应用暂时不可用",
    "applicationUnavailableDetail": "此应用遇到问题，无法继续显示当前页面。",
    "reloadApplication": "重新载入应用",
    "backToSite": "返回前台",
    "adminPanel": "管理后台",
    "adminBrand": "McWeb 管理后台",
    "developerMode": "开发模式",
    "developerModeBadge": "开发",
    "developerModeWarning": "安全校验和生产优化已关闭。",
    "developerModeProductionWarning": "当前正在生产环境中启用开发模式。",
    "developerTools": "开发工具",
    "openDeveloperTools": "打开开发工具",
    "developerProfile": "当前配置档",
    "developerEnvironment": "运行环境",
    "developerPageComponent": "页面组件",
    "developerRequestId": "请求 ID",
    "developerPersonas": "测试身份",
    "developerPersonasEmpty": "请先在开发工作台生成测试身份。",
    "developerCurrentPersona": "当前身份：",
    "developerPersona": {
      "owner": "站点所有者",
      "moderator": "版主",
      "member": "普通会员",
      "operator": "当前操作员"
    },
    "copyDeveloperDiagnostics": "复制脱敏诊断",
    "developerDiagnosticsCopied": "脱敏诊断已复制。",
    "developerDiagnosticsCopyFailed": "无法复制诊断信息。",
    "openDeveloperWorkbench": "打开开发工作台",
    "colon": "：",
    "listSeparator": "、",
    "notAvailable": "暂无",
    "reset": "重置",
    "apply": "应用",
    "moveUp": "上移",
    "moveDown": "下移",
    "download": "下载",
    "tableColumns": "显示列",
    "tableRange": "共 {count} 条 · 当前 {from}–{to} 条",
    "pagination": {
      "noResults": "暂无结果",
      "summary": "显示第 {from}–{to} 条，共 {count} 条",
      "previous": "上一页",
      "page": "第 {page} / {pages} 页",
      "next": "下一页"
    },
    "tableDensity": {
      "label": "表格密度",
      "comfortable": "宽松",
      "default": "默认",
      "compact": "紧凑"
    }
  },
  "locale": {
    "label": "语言",
    "zh-CN": "简体中文",
    "en": "English"
  },
  "components": {
    "bulkModerate": {
      "lockSelected": "锁定选中（{count}）",
      "unlockSelected": "解锁选中",
      "archiveSelected": "归档选中",
      "unarchiveSelected": "取消归档"
    },
    "topicList": {
      "colTopic": "主题",
      "colAuthor": "作者",
      "colReplies": "回复",
      "colViews": "浏览",
      "colLastReply": "最后回复",
      "empty": "暂无主题。"
    },
    "topicBadges": {
      "pinned": "[置顶]",
      "featured": "[精选]",
      "locked": "[锁定]",
      "announcement": "[公告]",
      "unlisted": "[未列出]",
      "archived": "[归档]",
      "solved": "[已解决]",
      "product": "[商品]",
      "unread": "{count} 未读"
    },
    "reactionUsers": {
      "title": "反应用户"
    },
    "tagGroupPicker": {
      "missingRequired": "请从以下必填标签组中至少选一个标签：{groups}",
      "atMaxTags": "已达标签上限（{max} 个）",
      "requiredGroup": "（必填组）",
      "onePerTopic": "（每组限选一个）",
      "selectedTags": "已选标签（可手动编辑）",
      "placeholder": "例如：公告,活动",
      "noGroups": "暂无标签组，请使用逗号分隔输入标签。"
    },
    "userHover": {
      "online": "· 在线",
      "posts": "{count} 帖",
      "likes": " · {count} 获赞",
      "trophies": " · {count} 奖杯积分",
      "memberSince": "加入于 {date}",
      "lastSeen": " · 最后在线 {date}",
      "viewProfile": "查看资料",
      "sendMessage": "发私信",
      "unfollow": "取消关注",
      "follow": "关注",
      "ingameOn": "· 游戏中 · {server}"
    },
    "markdownEditor": {
      "bold": "粗体",
      "italic": "斜体",
      "code": "代码",
      "link": "链接",
      "strikethrough": "删除线",
      "spoiler": "剧透",
      "quote": "引用",
      "heading": "标题",
      "bulletList": "列表",
      "codeBlock": "代码块",
      "table": "表格",
      "horizontalRule": "分隔线",
      "emoji": "表情",
      "emojiSearch": "搜索表情…",
      "emojiNoResults": "未找到表情",
      "uploadLevelHint": "Lv.1 后可上传图片",
      "previewing": "预览中…",
      "preview": "预览"
    },
    "richTextEditor": {
      "orderedList": "有序列表",
      "linkPrompt": "输入链接地址"
    },
    "postEditor": {
      "modeLabel": "编辑器:",
      "markdownMode": "Markdown",
      "wysiwygMode": "可视化",
      "wysiwygHint": "可视化编辑——内容仍以 Markdown 保存,与源码模式完全一致。"
    },
    "imageUpload": {
      "uploadFailed": "上传失败",
      "uploading": "上传中…",
      "insertImage": "插入图片"
    },
    "attachmentUpload": {
      "uploadFailed": "上传失败",
      "uploading": "上传中…",
      "scanning": "安全扫描中…",
      "scanFailed": "附件未通过安全扫描，无法使用。",
      "scanTimeout": "安全扫描耗时较长，请稍后重试。",
      "addAttachment": "添加附件",
      "uploadLevelHint": "Lv.1 后可上传附件",
      "pending": "待发布附件",
      "remove": "移除"
    },
    "fileInput": {
      "chooseFile": "选择文件"
    },
    "select": {
      "placeholder": "选择…"
    }
  }
} as Record<string, unknown>
