// Generated by scripts/generate-frontend-application-locales.mjs. Edit the full locale catalog, then regenerate.
export default {
  "website": {
    "layout": {
      "brand": "McWeb",
      "home": "首页",
      "about": "关于",
      "blog": "动态",
      "forum": "论坛",
      "store": "商城",
      "enterApp": "进入应用 →",
      "tagline": "面向 Minecraft 服主的开源社区与商城系统",
      "siteSection": "官网",
      "appSection": "应用中心",
      "signIn": "登录",
      "logoAlt": "站点标志",
      "copyright": "▣ {year} McWeb · 官网、社区与商城一体化"
    },
    "home": {
      "badge": "开源 Minecraft 服主管理系统",
      "heroLine1": "为你的",
      "heroLine2": "服务器",
      "heroLine3": "打造官网",
      "heroDesc": "论坛、商城与账号系统融为一体，让玩家轻松参与社区、获取资讯并管理订单。",
      "enterApp": "进入应用中心 →",
      "learnMore": "了解更多",
      "stat1Value": "3 合 1",
      "stat1Label": "官网 · 论坛 · 商城",
      "stat2Value": "玩家中心",
      "stat2Label": "账号 · 内容 · 订单",
      "stat3Value": "可定制",
      "stat3Label": "页面 · 主题 · 导航",
      "featuresLabel": "核心功能",
      "featuresTitle": "一站式服主工具箱",
      "featuresSubtitle": "从吸引新玩家到社区运营与付费转化，McWeb 把关键能力整合在同一套系统中。",
      "forumTitle": "社区论坛",
      "forumDesc": "分区讨论、话题追踪、私信与举报审核，让玩家在社区里自然留存。",
      "storeTitle": "数字商城",
      "storeDesc": "商品上架、购物车、支付回调与 Minecraft 自动发货，变现与运营一体化。",
      "identityTitle": "账号与安全",
      "identityDesc": "注册登录、邮箱验证、2FA 与细粒度权限，为服主团队提供可靠后台。",
      "storeSection": "商城",
      "featuredProducts": "精选商品",
      "allProducts": "全部商品 →",
      "announcements": "公告",
      "latestNews": "最新动态",
      "ctaLabel": "开始使用",
      "ctaTitle": "准备好上线你的服务器官网了吗？",
      "ctaDesc": "立即进入应用中心，体验论坛与商城；或通过后台自定义官网页面。",
      "registerFree": "免费注册",
      "viewAnnouncements": "查看公告"
    },
    "articles": {
      "title": "新闻与公告",
      "colTitle": "标题",
      "colType": "类型",
      "colPublished": "发布时间",
      "empty": "暂无已发布文章。",
      "backToBlog": "返回博客"
    },
    "pages": {
      "unknownBlock": "此内容暂时无法显示"
    }
  }
} as Record<string, unknown>
