test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

private_s3:
  service: S3
<% if ENV["MCWEB_S3_ACCESS_KEY_ID"].present? && ENV["MCWEB_S3_SECRET_ACCESS_KEY"].present? %>
  access_key_id: <%= ENV["MCWEB_S3_ACCESS_KEY_ID"].presence %>
  secret_access_key: <%= ENV["MCWEB_S3_SECRET_ACCESS_KEY"].presence %>
<% end %>
  region: <%= ENV["MCWEB_S3_REGION"] %>
  bucket: <%= ENV["MCWEB_S3_BUCKET"] %>
  public: false
  force_path_style: <%= ActiveModel::Type::Boolean.new.cast(ENV.fetch("MCWEB_S3_FORCE_PATH_STYLE", "0")) %>
<% if ENV["MCWEB_S3_ENDPOINT"].present? %>
  endpoint: <%= ENV["MCWEB_S3_ENDPOINT"] %>
<% end %>

# Remember not to checkin your GCS keyfile to a repository
# google:
#   service: GCS
#   project: your_project
#   credentials: <%= Rails.root.join("path/to/gcs.keyfile") %>
#   bucket: your_own_bucket-<%= Rails.env %>

# mirror:
#   service: Mirror
#   primary: local
#   mirrors: [ amazon, google, microsoft ]
