export const adminRoutes = {
  dashboard: '/admin',
  users: '/admin/users',
  user: (id: string) => `/admin/users/${id}`,
  roles: '/admin/roles',
  role: (key: string) => `/admin/roles/${key}`,
  auditLogs: '/admin/audit_logs',
  auditLog: (id: string | number) => `/admin/audit_logs/${id}`,
  forumSections: '/admin/forum/sections',
  newForumSection: '/admin/forum/sections/new',
  forumSection: (id: number) => `/admin/forum/sections/${id}`,
  editForumSection: (id: number) => `/admin/forum/sections/${id}/edit`,
  forumTopics: '/admin/forum/topics',
  forumTopic: (id: string | number) => `/admin/forum/topics/${id}`,
  forumReports: '/admin/forum/reports',
  forumReport: (id: string | number) => `/admin/forum/reports/${id}`,
  storeProducts: '/admin/store/products',
  storeCategories: '/admin/store/categories',
  storeCategory: (id: number) => `/admin/store/categories/${id}`,
  newStoreCategory: '/admin/store/categories/new',
  editStoreCategory: (id: number) => `/admin/store/categories/${id}/edit`,
  storeProduct: (id: string) => `/admin/store/products/${id}`,
  newStoreProduct: '/admin/store/products/new',
  editStoreProduct: (id: string) => `/admin/store/products/${id}/edit`,
  storeCoupons: '/admin/store/coupons',
  storeCoupon: (id: number) => `/admin/store/coupons/${id}`,
  newStoreCoupon: '/admin/store/coupons/new',
  editStoreCoupon: (id: number) => `/admin/store/coupons/${id}/edit`,
  storeOrders: '/admin/store/orders',
  storeReviews: '/admin/store/reviews',
  storeOrder: (id: string) => `/admin/store/orders/${id}`,
  storeFulfillments: '/admin/store/fulfillments',
  storeFulfillment: (id: string | number) => `/admin/store/fulfillments/${id}`,
  websitePages: '/admin/website/pages',
  websitePage: (id: string | number) => `/admin/website/pages/${id}`,
  websiteArticles: '/admin/website/articles',
  websiteArticle: (id: string) => `/admin/website/articles/${id}`,
  minecraftServers: '/admin/minecraft/servers',
  minecraftServer: (id: string | number) => `/admin/minecraft/servers/${id}`,
  settings: '/admin/system/settings',
  jobs: '/admin/system/jobs',
  site: '/',
} as const
