export const adminRoutes = {
  dashboard: '/admin',
  users: '/admin/users',
  user: (id: string) => `/admin/users/${id}`,
  roles: '/admin/roles',
  role: (key: string) => `/admin/roles/${key}`,
  auditLogs: '/admin/audit_logs',
  auditLog: (id: string | number) => `/admin/audit_logs/${id}`,
  forumSections: '/admin/forum/sections',
  forumCategories: '/admin/forum/categories',
  newForumCategory: '/admin/forum/categories/new',
  forumCategory: (id: number) => `/admin/forum/categories/${id}`,
  editForumCategory: (id: number) => `/admin/forum/categories/${id}/edit`,
  newForumSection: '/admin/forum/sections/new',
  forumSection: (id: number) => `/admin/forum/sections/${id}`,
  editForumSection: (id: number) => `/admin/forum/sections/${id}/edit`,
  forumTopics: '/admin/forum/topics',
  forumTopic: (id: string | number) => `/admin/forum/topics/${id}`,
  forumReports: '/admin/forum/reports',
  forumReport: (id: string | number) => `/admin/forum/reports/${id}`,
  forumApprovals: '/admin/forum/approvals',
  forumApproval: (id: number) => `/admin/forum/approvals/${id}`,
  forumUserFields: '/admin/forum/user-fields',
  editForumUserField: (id: number) => `/admin/forum/user-fields/${id}/edit`,
  newForumUserField: '/admin/forum/user-fields/new',
  forumBadges: '/admin/forum/badges',
  newForumBadge: '/admin/forum/badges/new',
  editForumBadge: (id: number) => `/admin/forum/badges/${id}/edit`,
  forumWarningTemplates: '/admin/forum/warning-templates',
  newForumWarningTemplate: '/admin/forum/warning-templates/new',
  editForumWarningTemplate: (id: number) => `/admin/forum/warning-templates/${id}/edit`,
  forumUserTitles: '/admin/forum/user-titles',
  newForumUserTitle: '/admin/forum/user-titles/new',
  editForumUserTitle: (id: number) => `/admin/forum/user-titles/${id}/edit`,
  forumUserGroups: '/admin/forum/user-groups',
  newForumUserGroup: '/admin/forum/user-groups/new',
  editForumUserGroup: (id: number) => `/admin/forum/user-groups/${id}/edit`,
  forumNotices: '/admin/forum/notices',
  newForumNotice: '/admin/forum/notices/new',
  editForumNotice: (id: number) => `/admin/forum/notices/${id}/edit`,
  forumStats: '/admin/forum/stats',
  forumScheduledTasks: '/admin/forum/scheduled-tasks',
  forumHelpArticles: '/admin/forum/help-articles',
  newForumHelpArticle: '/admin/forum/help-articles/new',
  editForumHelpArticle: (id: number) => `/admin/forum/help-articles/${id}/edit`,
  forumSmilies: '/admin/forum/smilies',
  newForumSmilie: '/admin/forum/smilies/new',
  editForumSmilie: (id: number) => `/admin/forum/smilies/${id}/edit`,
  forumCustomBbcodes: '/admin/forum/custom-bbcodes',
  newForumCustomBbcode: '/admin/forum/custom-bbcodes/new',
  editForumCustomBbcode: (id: number) => `/admin/forum/custom-bbcodes/${id}/edit`,
  forumAttachments: '/admin/forum/attachments',
  forumTags: '/admin/forum/tags',
  forumSettings: '/admin/forum/settings',
  forumWebhookDeliveries: '/admin/forum/webhook_deliveries',
  forumWebhookDelivery: (id: number | string) => `/admin/forum/webhook_deliveries/${id}`,
  forumEventWebhookDeliveries: '/admin/forum/event-webhook-deliveries',
  forumEventWebhookDelivery: (id: number | string) => `/admin/forum/event-webhook-deliveries/${id}`,
  newForumTag: '/admin/forum/tags/new',
  editForumTag: (id: number) => `/admin/forum/tags/${id}/edit`,
  ipBans: '/admin/system/ip_bans',
  emailBans: '/admin/system/email_bans',
  newEmailBan: '/admin/system/email_bans/new',
  emailBan: (id: number) => `/admin/system/email_bans/${id}`,
  storeProductQuestions: '/admin/store/product_questions',
  storeProducts: '/admin/store/products',
  storeCategories: '/admin/store/categories',
  storeCategory: (id: number) => `/admin/store/categories/${id}`,
  newStoreCategory: '/admin/store/categories/new',
  editStoreCategory: (id: number) => `/admin/store/categories/${id}/edit`,
  storeProduct: (id: string) => `/admin/store/products/${id}`,
  newStoreProduct: '/admin/store/products/new',
  editStoreProduct: (id: string) => `/admin/store/products/${id}/edit`,
  storeCoupons: '/admin/store/coupons',
  storeCoupon: (id: number) => `/admin/store/coupons/${id}`,
  newStoreCoupon: '/admin/store/coupons/new',
  editStoreCoupon: (id: number) => `/admin/store/coupons/${id}/edit`,
  storeMembershipTypes: '/admin/store/membership_types',
  storeMembershipType: (id: number) => `/admin/store/membership_types/${id}`,
  newStoreMembershipType: '/admin/store/membership_types/new',
  editStoreMembershipType: (id: number) => `/admin/store/membership_types/${id}/edit`,
  storeUserMemberships: '/admin/store/user_memberships',
  storeUserMembership: (id: number) => `/admin/store/user_memberships/${id}`,
  newStoreUserMembership: '/admin/store/user_memberships/new',
  storeGiftCards: '/admin/store/gift_cards',
  storeGiftCard: (id: number) => `/admin/store/gift_cards/${id}`,
  newStoreGiftCard: '/admin/store/gift_cards/new',
  editStoreGiftCard: (id: number) => `/admin/store/gift_cards/${id}/edit`,
  storeOrders: '/admin/store/orders',
  storeReviews: '/admin/store/reviews',
  storeOrder: (id: string) => `/admin/store/orders/${id}`,
  storeFulfillments: '/admin/store/fulfillments',
  storeWebhookDeliveries: '/admin/store/webhook_deliveries',
  storeWebhookDelivery: (id: number | string) => `/admin/store/webhook_deliveries/${id}`,
  storeSettings: '/admin/store/settings',
  storeFulfillment: (id: string | number) => `/admin/store/fulfillments/${id}`,
  websitePages: '/admin/website/pages',
  newWebsitePage: '/admin/website/pages/new',
  websitePage: (id: string | number) => `/admin/website/pages/${id}`,
  editWebsitePage: (id: string | number) => `/admin/website/pages/${id}/edit`,
  websiteArticles: '/admin/website/articles',
  newWebsiteArticle: '/admin/website/articles/new',
  websiteArticle: (id: string) => `/admin/website/articles/${id}`,
  editWebsiteArticle: (id: string) => `/admin/website/articles/${id}/edit`,
  websiteNavItems: '/admin/website/nav_items',
  websiteThemes: '/admin/website/themes',
  newWebsiteTheme: '/admin/website/themes/new',
  websiteTheme: (id: number | string) => `/admin/website/themes/${id}`,
  editWebsiteTheme: (id: number | string) => `/admin/website/themes/${id}/edit`,
  frontendTemplates: '/admin/frontend/templates',
  minecraftNodes: '/admin/minecraft/nodes',
  newMinecraftNode: '/admin/minecraft/nodes/new',
  editMinecraftNode: (id: string) => `/admin/minecraft/nodes/${id}/edit`,
  minecraftNode: (id: string | number) => `/admin/minecraft/nodes/${id}`,
  minecraftPlayers: '/admin/minecraft/players',
  minecraftServers: '/admin/minecraft/servers',
  newMinecraftServer: '/admin/minecraft/servers/new',
  editMinecraftServer: (id: string) => `/admin/minecraft/servers/${id}/edit`,
  minecraftSettings: '/admin/minecraft/settings',
  minecraftIntegrationActions: '/admin/minecraft/integration-actions',
  minecraftProfileFields: '/admin/minecraft/profile-fields',
  minecraftPermissionMappings: '/admin/minecraft/permission-group-mappings',
  minecraftServer: (id: string | number) => `/admin/minecraft/servers/${id}`,
  settings: '/admin/system/settings',
  featureToggles: '/admin/system/feature-toggles',
  applications: '/admin/system/applications',
  jobs: '/admin/system/jobs',
  site: '/',
} as const
