export const appPrefix = '/app' as const

export const routes = {
  home: '/',
  app: appPrefix,
  forum: `${appPrefix}/forum/sections`,
  forumLatest: `${appPrefix}/forum/latest`,
  forumTop: `${appPrefix}/forum/top`,
  forumNew: `${appPrefix}/forum/new`,
  forumNewDismiss: `${appPrefix}/forum/new/dismiss`,
  forumActivity: `${appPrefix}/forum/activity`,
  forumFollowing: `${appPrefix}/forum/following`,
  forumMentionSearch: `${appPrefix}/forum/mentions/search`,
  forumTagSuggest: `${appPrefix}/forum/tag-suggest`,
  forumSection: (slug: string) => `${appPrefix}/forum/sections/${slug}`,
  forumTopic: (id: string) => `${appPrefix}/forum/topics/${id}`,
  newForumTopic: (sectionSlug: string) => `${appPrefix}/forum/topics/new?section_id=${sectionSlug}`,
  forumSearch: `${appPrefix}/forum/search`,
  forumWatching: `${appPrefix}/forum/watching`,
  forumWatchedTags: `${appPrefix}/forum/watching/tags`,
  forumWatchedTagTopics: `${appPrefix}/forum/watching/tag-topics`,
  forumBookmarks: `${appPrefix}/forum/bookmarks`,
  forumBlocks: `${appPrefix}/forum/blocks`,
  forumIgnores: `${appPrefix}/forum/ignores`,
  forumMuted: `${appPrefix}/forum/muted`,
  forumMembers: `${appPrefix}/forum/members`,
  forumStaff: `${appPrefix}/forum/staff`,
  forumStatistics: `${appPrefix}/forum/statistics`,
  forumLeaderboard: `${appPrefix}/forum/leaderboard`,
  forumUnread: `${appPrefix}/forum/unread`,
  forumAssigned: `${appPrefix}/forum/assigned`,
  forumUnreadMarkAllRead: `${appPrefix}/forum/unread/mark_all_read`,
  forumPreview: `${appPrefix}/forum/preview`,
  forumTags: `${appPrefix}/forum/tags`,
  forumBadges: `${appPrefix}/forum/badges`,
  forumBadge: (slug: string) => `${appPrefix}/forum/badges/${slug}`,
  forumNotifications: `${appPrefix}/forum/notifications`,
  forumPreferences: `${appPrefix}/forum/preferences`,
  forumDrafts: `${appPrefix}/forum/drafts`,
  forumModerationApprovals: `${appPrefix}/forum/moderation/approvals`,
  forumLatestRss: `${appPrefix}/forum/latest.rss`,
  forumSectionRss: (slug: string) => `${appPrefix}/forum/sections/${slug}.rss`,
  forumTagRss: (slug: string) => `${appPrefix}/forum/tags/${slug}.rss`,
  forumSitemap: `${appPrefix}/forum/sitemap.xml`,
  forumMessages: `${appPrefix}/forum/conversations`,
  forumMessagesNew: `${appPrefix}/forum/conversations/new`,
  forumMessagesGroupNew: `${appPrefix}/forum/conversations/new?group=1`,
  forumMessage: (id: number) => `${appPrefix}/forum/conversations/${id}`,
  forumUser: (username: string) => `${appPrefix}/forum/users/${username}`,
  forumUserFollowers: (username: string) => `${appPrefix}/forum/users/${username}/followers`,
  forumTag: (slug: string) => `${appPrefix}/forum/tags/${slug}`,
  forumReport: `${appPrefix}/forum/reports/new`,
  store: `${appPrefix}/store/products`,
  storeRecentlyViewed: `${appPrefix}/store/products/recently_viewed`,
  storeCompare: `${appPrefix}/store/compare`,
  storeToggleCompare: (productId: string) => `${appPrefix}/store/compare/toggle?product_id=${productId}`,
  storeImportWishlistCompare: `${appPrefix}/store/compare/import_wishlist`,
  storeWishlist: `${appPrefix}/store/wishlist`,
  storeWishlistFilterPresets: `${appPrefix}/store/wishlist/filter_presets`,
  storeStockAlerts: `${appPrefix}/store/stock_alerts`,
  storePriceAlerts: `${appPrefix}/store/price_alerts`,
  storeAvailabilityAlerts: `${appPrefix}/store/availability_alerts`,
  storeProductPreview: (id: string) => `${appPrefix}/store/products/${id}/preview`,
  storeProduct: (id: string) => `${appPrefix}/store/products/${id}`,
  storeCart: `${appPrefix}/store/cart`,
  storeCheckout: `${appPrefix}/store/checkout`,
  storeOrders: `${appPrefix}/store/orders`,
  storeOrder: (id: string) => `${appPrefix}/store/orders/${id}`,
  storeOrderReceiptPdf: (id: string) => `${appPrefix}/store/orders/${id}/receipt_pdf`,
  storeCoupon: (code: string) => `${appPrefix}/store/coupons/${code}`,
  storeGiftCard: (code: string) => `${appPrefix}/store/gift_cards/${code}`,
  storeGiftCards: `${appPrefix}/store/gift_cards`,
  storeCategory: (slug: string) => `${appPrefix}/store/categories/${slug}`,
  storeCategoryRss: (slug: string) => `${appPrefix}/store/categories/${slug}.rss`,
  storeLatestRss: `${appPrefix}/store/latest.rss`,
  storeShippingAddresses: `${appPrefix}/store/shipping_addresses`,
  storeWallet: `${appPrefix}/store/wallet`,
  storePreferences: `${appPrefix}/store/preferences`,
  storeWishlistShare: `${appPrefix}/store/wishlist/share`,
  storePublicWishlist: (token: string) => `${appPrefix}/store/wishlist/${token}`,
  forumUpload: `${appPrefix}/forum/uploads`,
  forumAttachments: `${appPrefix}/forum/attachments`,
  signIn: `${appPrefix}/identity/sign-in`,
  identitySession: `${appPrefix}/identity/session`,
  register: `${appPrefix}/identity/register`,
  identityPasswordResets: `${appPrefix}/identity/password_resets`,
  passwordReset: `${appPrefix}/identity/password_resets/new`,
  signOut: `${appPrefix}/identity/session`,
  sessionsManagement: `${appPrefix}/identity/sessions`,
  security: `${appPrefix}/identity/security`,
  securityTotpSetup: `${appPrefix}/identity/security/totp/setup`,
  securityTotpConfirm: `${appPrefix}/identity/security/totp/confirm`,
  securityTotpDisable: `${appPrefix}/identity/security/totp/disable`,
  resendVerification: `${appPrefix}/identity/resend-verification`,
  blog: '/blog',
  blogArticle: (slug: string) => `/blog/${slug}`,
  page: (slug: string) => `/${slug}`,
  minecraftLink: `${appPrefix}/minecraft/link`,
  locale: '/locale',
} as const
