export const routes = {
  home: '/',
  forum: '/forum/sections',
  forumSection: (slug: string) => `/forum/sections/${slug}`,
  forumTopic: (id: string) => `/forum/topics/${id}`,
  newForumTopic: (sectionSlug: string) => `/forum/topics/new?section_id=${sectionSlug}`,
  forumSearch: '/forum/search',
  forumWatching: '/forum/watching',
  forumNotifications: '/forum/notifications',
  forumUser: (username: string) => `/forum/users/${username}`,
  forumTag: (slug: string) => `/forum/tags/${slug}`,
  forumReport: '/forum/reports/new',
  store: '/store/products',
  storeProduct: (id: string) => `/store/products/${id}`,
  storeCart: '/store/cart',
  storeCheckout: '/store/checkout',
  storeOrders: '/store/orders',
  storeOrder: (id: string) => `/store/orders/${id}`,
  signIn: '/identity/sign-in',
  register: '/identity/register',
  passwordReset: '/identity/password_resets/new',
  sessions: '/identity/sessions',
  blog: '/website/blog',
  blogArticle: (slug: string) => `/website/blog/${slug}`,
  page: (slug: string) => `/website/pages/${slug}`,
  minecraftLink: '/minecraft/link',
} as const
