export const routes = {
  home: '/',
  forum: '/forum/sections',
  forumLatest: '/forum/latest',
  forumActivity: '/forum/activity',
  forumFollowing: '/forum/following',
  forumMentionSearch: '/forum/mentions/search',
  forumSection: (slug: string) => `/forum/sections/${slug}`,
  forumTopic: (id: string) => `/forum/topics/${id}`,
  newForumTopic: (sectionSlug: string) => `/forum/topics/new?section_id=${sectionSlug}`,
  forumSearch: '/forum/search',
  forumWatching: '/forum/watching',
  forumBookmarks: '/forum/bookmarks',
  forumUnread: '/forum/unread',
  forumUnreadMarkAllRead: '/forum/unread/mark_all_read',
  forumPreview: '/forum/preview',
  forumTags: '/forum/tags',
  forumNotifications: '/forum/notifications',
  forumPreferences: '/forum/preferences',
  forumDrafts: '/forum/drafts',
  forumLatestRss: '/forum/latest.rss',
  forumSectionRss: (slug: string) => `/forum/sections/${slug}.rss`,
  forumTagRss: (slug: string) => `/forum/tags/${slug}.rss`,
  forumSitemap: '/forum/sitemap.xml',
  forumMessages: '/forum/conversations',
  forumMessagesNew: '/forum/conversations/new',
  forumMessagesGroupNew: '/forum/conversations/new?group=1',
  forumMessage: (id: number) => `/forum/conversations/${id}`,
  forumUser: (username: string) => `/forum/users/${username}`,
  forumTag: (slug: string) => `/forum/tags/${slug}`,
  forumReport: '/forum/reports/new',
  store: '/store/products',
  storeWishlist: '/store/wishlist',
  storeProduct: (id: string) => `/store/products/${id}`,
  storeCart: '/store/cart',
  storeCheckout: '/store/checkout',
  storeOrders: '/store/orders',
  storeOrder: (id: string) => `/store/orders/${id}`,
  storeOrderReceiptPdf: (id: string) => `/store/orders/${id}/receipt_pdf`,
  storePreferences: '/store/preferences',
  storeWishlistShare: '/store/wishlist/share',
  storePublicWishlist: (token: string) => `/store/wishlist/${token}`,
  forumUpload: '/forum/uploads',
  signIn: '/identity/sign-in',
  register: '/identity/register',
  passwordReset: '/identity/password_resets/new',
  sessions: '/identity/sessions',
  blog: '/website/blog',
  blogArticle: (slug: string) => `/website/blog/${slug}`,
  page: (slug: string) => `/website/pages/${slug}`,
  minecraftLink: '/minecraft/link',
} as const
