// Generated by scripts/generate-frontend-application-locales.mjs. Edit the full locale catalog, then regenerate.
export default {
  "nav": {
    "sections": "Sections",
    "latest": "Latest",
    "top": "Top",
    "new": "New",
    "activity": "Activity",
    "search": "Search",
    "tags": "Tags",
    "badges": "Badges",
    "members": "Members",
    "staff": "Staff",
    "staffWorkspace": "Staff workspace",
    "statistics": "Statistics",
    "help": "Help",
    "watching": "Watching",
    "watchedTags": "Watched tags",
    "watchedTagTopics": "Tag topics",
    "following": "Following",
    "bookmarks": "Bookmarks",
    "unread": "Unread",
    "assigned": "Assigned",
    "moderationApprovals": "Pending approval",
    "messages": "Messages",
    "drafts": "Drafts",
    "preferences": "Preferences",
    "blocks": "Blocks",
    "ignores": "Ignores",
    "muted": "Muted",
    "products": "Products",
    "compare": "Compare",
    "recentlyViewed": "Recently viewed",
    "orders": "My orders",
    "wishlist": "Wishlist",
    "shippingAddresses": "Addresses",
    "wallet": "Store credit",
    "giftCards": "Gift cards",
    "stockAlerts": "Stock alerts",
    "priceAlerts": "Price alerts",
    "availabilityAlerts": "Availability alerts",
    "storePreferences": "Store notifications",
    "cart": "Cart",
    "personal": "My",
    "forum": "Forum",
    "store": "Store"
  },
  "portal": {
    "userCenter": "Account",
    "profile": "Profile",
    "forumPreferences": "Forum preferences",
    "brand": "McWeb",
    "backToWebsite": "Back to website",
    "serverStatus": "Server status",
    "serverStatusOnline": "Online",
    "serverStatusOffline": "Offline",
    "serverStatusMaintenance": "Maintenance",
    "serverAnomalyHint": "One or more servers need attention",
    "online": "online"
  },
  "breadcrumb": {
    "home": "Home",
    "account": "Account",
    "forum": "Forum",
    "store": "Store",
    "label": "Breadcrumb"
  },
  "accountCenter": {
    "title": "Account center",
    "overview": "Overview",
    "subtitle": "Review your identity, security, and items that need attention.",
    "open": "Open",
    "openItem": "Open {item}",
    "actions": {
      "profile": "Edit profile",
      "password": "Change password",
      "security": "Security settings",
      "minecraft": "Minecraft accounts"
    },
    "status": {
      "verified": "Verified",
      "unverified": "Unverified",
      "enabled": "Enabled",
      "disabled": "Disabled"
    },
    "identity": {
      "title": "Account details",
      "username": "Username",
      "language": "Language",
      "joinedAt": "Joined"
    },
    "security": {
      "title": "Security status",
      "email": "Email",
      "twoFactor": "Two-factor authentication",
      "sessions": "Active sessions",
      "review": "Review security"
    },
    "activity": {
      "title": "Needs your attention",
      "notifications": "Unread notifications",
      "messages": "Unread messages",
      "drafts": "Saved topic drafts",
      "open": "View details"
    },
    "minecraft": {
      "title": "Primary Minecraft identity",
      "unbound": "No Minecraft identity is linked yet.",
      "bind": "Link an account",
      "manage": "Manage linked accounts"
    },
    "groups": {
      "community": "Community activity",
      "content": "Content and conversations",
      "account": "Account and privacy",
      "moreCommunity": "More community tools",
      "privacy": "Community privacy"
    },
    "items": {
      "newTopics": {
        "title": "New topics",
        "description": "Catch up on topics since your last visit."
      },
      "unread": {
        "title": "Unread",
        "description": "Resume reading topics you have not finished."
      },
      "watching": {
        "title": "Watched topics",
        "description": "Manage the topics you follow."
      },
      "following": {
        "title": "Following",
        "description": "See activity from members you follow."
      },
      "watchedTags": {
        "title": "Watched tags",
        "description": "Manage the tags you follow."
      },
      "watchedTagTopics": {
        "title": "Tag topics",
        "description": "Browse topics from your watched tags."
      },
      "bookmarks": {
        "title": "Bookmarks",
        "description": "Return to saved posts and topics."
      },
      "messages": {
        "title": "Messages",
        "description": "Read and manage your private conversations."
      },
      "drafts": {
        "title": "Drafts",
        "description": "Continue writing saved topics and replies."
      },
      "preferences": {
        "title": "Community preferences",
        "description": "Adjust how the community works for you."
      },
      "blocks": {
        "title": "Blocked members",
        "description": "Review members you have blocked."
      },
      "ignores": {
        "title": "Ignored members",
        "description": "Review members whose content you hide."
      },
      "muted": {
        "title": "Muted content",
        "description": "Manage muted topics and sections."
      },
      "security": {
        "title": "Security",
        "description": "Manage email, two-factor authentication, and account closure."
      },
      "sessions": {
        "title": "Sessions",
        "description": "Review and revoke signed-in devices."
      },
      "dataExports": {
        "title": "Data exports",
        "description": "Request and download a copy of your data."
      },
      "minecraft": {
        "title": "Minecraft accounts",
        "description": "Link and manage your Minecraft identities."
      }
    }
  },
  "accountNotifications": {
    "title": "Notifications",
    "markAllRead": "Mark all read",
    "dismissAlerts": "Dismiss alerts",
    "alert": "Alert",
    "all": "All",
    "allMessages": "All messages",
    "unread": "Unread",
    "categoryFilter": "Category:",
    "readFilter": "Read state:",
    "typeFilter": "Notification type:",
    "timeFilter": "Time:",
    "quickFilter": "Quick filters:",
    "unreadCount": "{count} unread",
    "activeFilters": "Active filters:",
    "removeFilter": "Remove filter",
    "clearAll": "Clear all",
    "collapse": "Collapse",
    "expand": "Expand",
    "view": "View",
    "markRead": "Read",
    "delete": "Delete",
    "deleteTitle": "Delete notification",
    "deleteConfirm": "Delete this notification? This cannot be undone.",
    "empty": "No notifications yet."
  },
  "auth": {
    "passwordReset": {
      "title": "Reset password",
      "subtitle": "Enter your email to receive a reset link",
      "email": "Email",
      "submit": "Send reset link",
      "backToSignIn": "Back to sign in",
      "editTitle": "Set new password",
      "editSubtitle": "Enter your new password",
      "newPassword": "New password",
      "confirmPassword": "Confirm password",
      "updatePassword": "Update password",
      "failed": "Reset failed",
      "sendFailed": "Could not send",
      "updateFailed": "Could not update password"
    },
    "signIn": {
      "title": "Sign in",
      "subtitle": "Access your Mcweb account",
      "failed": "Sign in failed",
      "email": "Email",
      "password": "Password",
      "totp": "Two-factor code (if enabled)",
      "rememberMe": "Remember me",
      "createAccount": "Create account",
      "lostTwoFactor": "Lost access to two-factor authentication?"
    },
    "twoFactor": {
      "title": "Two-factor authentication",
      "subtitle": "Enter a code from your authenticator or an account recovery code",
      "code": "Authentication or recovery code",
      "verify": "Continue signing in",
      "failed": "Verification failed",
      "backToSignIn": "Back to sign in",
      "recover": "Cannot use your authenticator?"
    },
    "register": {
      "title": "Create account",
      "subtitle": "Join the Mcweb community",
      "failed": "Registration failed",
      "email": "Email",
      "username": "Username",
      "displayName": "Display name",
      "password": "Password",
      "locale": "Language",
      "timeZone": "Time zone",
      "hasAccount": "Already have an account? Sign in"
    }
  },
  "identity": {
    "profile": {
      "title": "Edit profile",
      "subtitle": "Keep your public name and application language up to date",
      "accountIdentity": "Account identity",
      "editableDetails": "Profile preferences",
      "username": "Username",
      "email": "Email",
      "readOnlyHint": "Username and email are managed through their dedicated account flows.",
      "displayName": "Display name",
      "displayNameHint": "Optional, up to 64 characters. Control characters are not accepted.",
      "displayNamePlaceholder": "How your name should appear",
      "language": "Application language",
      "languageHint": "This changes the language for this session and future visits.",
      "save": "Save profile"
    },
    "password": {
      "title": "Change password",
      "subtitle": "Confirm your identity before replacing your sign-in password",
      "formTitle": "Password and verification",
      "sessionNotice": "After the change, this device stays signed in and every other session is signed out.",
      "currentPassword": "Current password",
      "newPassword": "New password",
      "confirmPassword": "Confirm new password",
      "passwordHint": "Use at least 6 characters and do not reuse your current password.",
      "twoFactorCode": "Two-factor or recovery code",
      "twoFactorHint": "Enter the current authenticator code or one unused recovery code.",
      "twoFactorPlaceholder": "One-time code",
      "submit": "Change password",
      "cancel": "Back to security"
    },
    "sessions": {
      "title": "Active sessions",
      "subtitle": "Manage your signed-in devices",
      "colIp": "IP",
      "colDevice": "Device",
      "colLastActive": "Last active",
      "current": "Current",
      "revoke": "Revoke"
    },
    "security": {
      "title": "Account security",
      "subtitle": "Manage email, two-factor authentication, recovery, and account status",
      "changePassword": "Change password",
      "emailTitle": "Email verification",
      "emailHint": "Sensitive changes require your password and two-factor code.",
      "verified": "Verified",
      "unverified": "Unverified",
      "changeEmailTitle": "Change email",
      "changeEmailHint": "Your current email stays active until you confirm the replacement address.",
      "newEmail": "New email",
      "changeEmail": "Send confirmation to new email",
      "pendingEmailTitle": "Email change awaiting confirmation",
      "pendingEmailDescription": "Confirm {email} from its inbox to finish the change. A cancellation link was sent to your current email.",
      "pendingEmailExpires": "Confirmation expires {at}.",
      "totpTitle": "Two-factor authentication",
      "totpHint": "Use an authenticator app to generate one-time codes.",
      "enabled": "Enabled",
      "disabled": "Disabled",
      "requiredNotice": "An administrator requires two-factor authentication before you can continue.",
      "scanQr": "Scan the QR code with your authenticator app, or enter the secret manually.",
      "startTotp": "Set up two-factor authentication",
      "confirmTotpHint": "Re-enter your password to protect enrollment. Enabling two-factor authentication signs out every other device.",
      "confirmTotp": "Confirm and enable",
      "disableTotp": "Disable two-factor authentication",
      "disableTotpHint": "Your current authenticator secret and all recovery codes become invalid immediately.",
      "recoveryCodesTitle": "Recovery codes",
      "recoveryCodesRemaining": "Recovery codes remaining: {count}",
      "recoveryCodesOneTimeTitle": "Save your recovery codes now",
      "recoveryCodesOneTimeHint": "These codes are shown once. Each code can be used only once, so store them securely.",
      "copyRecoveryCodes": "Copy recovery codes",
      "downloadRecoveryCodes": "Download text file",
      "recoveryCodesCopied": "Recovery codes copied.",
      "recoveryCodesCopyFailed": "Automatic copy failed. Select and save the codes manually.",
      "recoveryCodesDownloaded": "Recovery-code file downloaded.",
      "recoveryCodesAcknowledgement": "I saved these codes securely and understand they will not be shown again after leaving this page.",
      "finishRecoveryCodes": "I saved them securely",
      "regenerateRecoveryCodes": "Regenerate recovery codes",
      "regenerateRecoveryCodesHint": "Regenerating immediately revokes every old code and requires your password and current code.",
      "closeAccountTitle": "Close account",
      "closeAccountHint": "This self-service closure is irreversible. Review the data outcomes before continuing.",
      "closeAccountProfile": "Email, username, display name, biography, avatar, and security credentials are removed or anonymized.",
      "closeAccountContent": "Published content is retained under a stable anonymous author so discussions remain intact.",
      "closeAccountRecords": "Orders, payments, refunds, moderation evidence, and audit records remain under legal and product retention rules.",
      "closeAccountSessions": "Every sign-in session and API key is revoked immediately.",
      "closeAccountConfirmation": "Type DELETE to confirm closure",
      "closeAccountConfirmationPlaceholder": "DELETE",
      "closeAccountReason": "Reason for closing (optional)",
      "closeAccountReasonPlaceholder": "Help us understand your decision. Do not include passwords or other sensitive information.",
      "closeAccountContentChoice": "Choose how your authored community content should be handled",
      "closeAccountAnonymize": "Keep discussions under a stable anonymous author",
      "closeAccountAnonymizeHint": "Your profile identity is removed while published discussions remain readable and structurally intact.",
      "closeAccountDeleteContent": "Request removal of authored community content",
      "closeAccountDeleteContentHint": "Eligible topics, posts, and private messages are removed. Protected evidence and governed records remain.",
      "closeAccountLegalHoldHint": "An unresolved report or legal hold can override deletion. Your final outcome is recorded without exposing protected evidence.",
      "closeAccount": "Permanently close account"
    },
    "dataExports": {
      "title": "Your data exports",
      "subtitle": "Create and manage a private archive of your McWeb account data",
      "request": "Request new export",
      "privacyTitle": "Private, temporary download",
      "privacyDescription": "Exports expire after {hours} hours and are limited to {limit} requests per 24 hours. Revoking an export removes its file.",
      "emptyTitle": "No data exports yet",
      "emptyDescription": "Request an export to generate a ZIP archive in the background.",
      "history": "Data export history",
      "exportLabel": "Account data archive",
      "requestedAt": "Requested",
      "expiresAt": "Expires",
      "attempts": "Attempts",
      "totalRecords": "{count} records included",
      "recordCount": "{count} records",
      "moduleSummary": "Records included by module",
      "olderHistory": "View older exports",
      "download": "Download ZIP",
      "retry": "Retry",
      "revoke": "Revoke",
      "revokeConfirm": "Revoke this export and remove its download file?",
      "failedDescription": "Generation failed without exposing internal error details. You can retry safely.",
      "tooLargeDescription": "This account archive exceeded the export size limit. Contact support to arrange a scoped export.",
      "resourceExhaustedDescription": "The export service ran out of capacity while building this archive. Retry later; your source data was not changed.",
      "recoveryDescription": "Background processing stopped before this archive became ready. Restart this export to continue safely.",
      "backToSecurity": "Back to account security",
      "modules": {
        "identityProfile": "Account profile",
        "identityNotifications": "Notifications",
        "communityContent": "Community content",
        "communityActivity": "Community activity",
        "communityUploads": "Uploads",
        "communityReportCases": "Reports and appeals",
        "commerceAccount": "Commerce account data",
        "commerceActivity": "Commerce activity",
        "minecraftAccounts": "Minecraft accounts",
        "secureEvidenceAttachments": "Evidence attachments"
      },
      "status": {
        "queued": "Queued",
        "running": "Generating",
        "completed": "Ready",
        "failed": "Failed",
        "revoked": "Revoked",
        "expired": "Expired"
      }
    },
    "totpRecovery": {
      "requestTitle": "Recover two-factor access",
      "requestSubtitle": "Request a one-time recovery link through your verified email",
      "securityTitle": "Account status stays private",
      "securityHint": "The result is identical whether the address exists or not. Recovery links expire after 30 minutes.",
      "send": "Send recovery link",
      "completeTitle": "Reset two-factor authentication",
      "completeSubtitle": "Verify your account password to remove the old authenticator and recovery codes",
      "failedTitle": "Recovery could not be completed",
      "sessionWarningTitle": "Security notice",
      "sessionWarning": "A successful reset revokes every current session. You must sign in again and configure a new authenticator.",
      "reset": "Reset two-factor authentication and revoke sessions"
    },
    "resendVerification": {
      "title": "Resend verification email",
      "subtitle": "Enter your registration email to receive a new link",
      "hint": "We do not reveal whether an account exists; unverified addresses may receive a new email.",
      "submit": "Send verification email"
    }
  },
  "minecraft": {
    "title": "Minecraft",
    "link": {
      "title": "Link Minecraft account",
      "subtitle": "Run /website link in-game, then enter the code here",
      "code": "Verification code",
      "submit": "Link account",
      "notLinked": "No Minecraft account linked yet.",
      "goLink": "Link now",
      "lastSeen": "Last seen in-game",
      "lastSeenAt": "Last seen in-game: {time}",
      "fullBody": "Full body",
      "playerId": "Player ID: {id}",
      "boundAccountsTitle": "Your linked Minecraft accounts",
      "addAccountTitle": "Link another Minecraft account",
      "primaryAccount": "Primary account",
      "setPrimaryAccount": "Set as primary",
      "requestPrimaryAccount": "Request primary-account change",
      "primaryPolicyImmediate": "Primary-account changes take effect immediately.",
      "primaryPolicyStaffApproval": "Primary-account changes require staff approval. Requests expire after {hours} hours.",
      "primaryPolicyAdministratorOnly": "Only an authorized administrator can change the primary account.",
      "primaryCooldownActive": "You can change the primary account again after {time}.",
      "pendingPrimaryRequestTitle": "A primary-account request is pending",
      "pendingPrimaryRequestBody": "Requested account: {account}. The request expires at {time}.",
      "cancelPrimaryRequest": "Cancel request",
      "primaryRequestReason": "Reason for the change",
      "primaryRequestReasonHelp": "Staff will use this context when reviewing the request.",
      "primaryRequestReasonPlaceholder": "Explain why this account should become primary…",
      "skinCached": "Skin cached locally",
      "skinCachePending": "Local skin cache pending",
      "linkedAt": "Linked {time}",
      "unlinkAccount": "Unlink account",
      "unlinkAccountLabel": "Unlink Minecraft account {account}",
      "unlinkTitle": "Unlink Minecraft account",
      "unlinkConfirmAction": "Unlink this account",
      "unlinkWarningTitle": "This removes the account from your website profile",
      "unlinkWarningBody": "Review the selected account and consequences before continuing.",
      "unlinkConsequencesTitle": "What happens next",
      "unlinkConsequenceAccess": "Website features will stop treating this Minecraft identity as linked to you.",
      "unlinkConsequencePrimary": "If this is your primary account, the oldest remaining linked account becomes primary automatically.",
      "unlinkConsequenceRequests": "Pending primary-account requests involving this account are cancelled.",
      "unlinkConsequenceRelink": "To use this identity again, you must complete the in-game linking flow again.",
      "unlinkConfirmationLabel": "Confirm the account name",
      "unlinkConfirmationHelp": "Type {account} exactly to confirm this specific account."
    }
  }
} as Record<string, unknown>
