// Generated by scripts/generate-frontend-application-locales.mjs. Edit the full locale catalog, then regenerate.
export default {
  "common": {
    "cancel": "Cancel",
    "confirm": "Confirm",
    "close": "Close",
    "save": "Save",
    "signIn": "Sign in",
    "signOut": "Sign out",
    "signOutConfirmTitle": "Sign out?",
    "signOutConfirmDescription": "Your current session will end on this device.",
    "refresh": "Refresh",
    "register": "Register",
    "loading": "Loading…",
    "browse": "Browse",
    "back": "Back",
    "view": "View",
    "preview": "Preview",
    "edit": "Edit",
    "delete": "Delete",
    "actions": "Actions",
    "mine": "Mine",
    "personal": "My",
    "announcement": "Announcement",
    "closeAnnouncement": "Dismiss announcements",
    "openMenu": "Open menu",
    "navigation": "Primary navigation",
    "skipToContent": "Skip to content",
    "toggleTheme": "Toggle theme",
    "notifications": "Notifications",
    "messages": "Messages",
    "cart": "Cart",
    "applicationUnavailable": "Application unavailable",
    "applicationUnavailableDetail": "This application encountered a problem and cannot display the current page.",
    "reloadApplication": "Reload application",
    "backToSite": "Back to site",
    "adminPanel": "Admin",
    "adminBrand": "McWeb Admin",
    "developerMode": "Developer mode",
    "developerModeBadge": "DEV",
    "developerModeWarning": "Security checks and production optimizations are disabled.",
    "developerModeProductionWarning": "Developer mode is active in the production environment.",
    "developerTools": "Developer tools",
    "openDeveloperTools": "Open developer tools",
    "developerProfile": "Active profile",
    "developerEnvironment": "Environment",
    "developerPageComponent": "Page component",
    "developerRequestId": "Request ID",
    "developerPersonas": "Test personas",
    "developerPersonasEmpty": "Seed the persona scenario in Developer Workbench first.",
    "developerCurrentPersona": "Current persona:",
    "developerPersona": {
      "owner": "Owner",
      "moderator": "Moderator",
      "member": "Member",
      "operator": "Operator"
    },
    "copyDeveloperDiagnostics": "Copy redacted diagnostics",
    "developerDiagnosticsCopied": "Redacted diagnostics copied.",
    "developerDiagnosticsCopyFailed": "Could not copy diagnostics.",
    "openDeveloperWorkbench": "Open Developer Workbench",
    "colon": ":",
    "listSeparator": ", ",
    "notAvailable": "Not available",
    "reset": "Reset",
    "apply": "Apply",
    "moveUp": "Move up",
    "moveDown": "Move down",
    "download": "Download",
    "tableColumns": "Columns",
    "tableRange": "{count} total · {from}–{to}",
    "pagination": {
      "noResults": "No results",
      "summary": "Showing {from}–{to} of {count}",
      "previous": "Previous",
      "page": "Page {page} / {pages}",
      "next": "Next"
    },
    "tableDensity": {
      "label": "Table density",
      "comfortable": "Comfortable",
      "default": "Default",
      "compact": "Compact"
    }
  },
  "locale": {
    "label": "Language",
    "zh-CN": "简体中文",
    "en": "English"
  },
  "components": {
    "bulkModerate": {
      "lockSelected": "Lock selected ({count})",
      "unlockSelected": "Unlock selected",
      "archiveSelected": "Archive selected",
      "unarchiveSelected": "Unarchive selected"
    },
    "topicList": {
      "colTopic": "Topic",
      "colAuthor": "Author",
      "colReplies": "Replies",
      "colViews": "Views",
      "colLastReply": "Last reply",
      "empty": "No topics yet."
    },
    "topicBadges": {
      "pinned": "[Pinned]",
      "featured": "[Featured]",
      "locked": "[Locked]",
      "announcement": "[Announcement]",
      "unlisted": "[Unlisted]",
      "archived": "[Archived]",
      "solved": "[Solved]",
      "product": "[Product]",
      "unread": "{count} unread"
    },
    "reactionUsers": {
      "title": "Reactions"
    },
    "tagGroupPicker": {
      "missingRequired": "Pick at least one tag from: {groups}",
      "atMaxTags": "Tag limit reached ({max})",
      "requiredGroup": "(required)",
      "onePerTopic": "(one per group)",
      "selectedTags": "Selected tags (editable)",
      "placeholder": "e.g. news,event",
      "noGroups": "No tag groups — enter comma-separated tags."
    },
    "userHover": {
      "online": "· Online",
      "posts": "{count} posts",
      "likes": " · {count} likes",
      "trophies": " · {count} trophy points",
      "memberSince": "Joined {date}",
      "lastSeen": " · Last seen {date}",
      "viewProfile": "View profile",
      "sendMessage": "Message",
      "unfollow": "Unfollow",
      "follow": "Follow",
      "ingameOn": "· In-game on {server}"
    },
    "markdownEditor": {
      "bold": "Bold",
      "italic": "Italic",
      "code": "Code",
      "link": "Link",
      "strikethrough": "Strike",
      "spoiler": "Spoiler",
      "quote": "Quote",
      "heading": "Heading",
      "bulletList": "List",
      "codeBlock": "Code block",
      "table": "Table",
      "horizontalRule": "Divider",
      "emoji": "Emoji",
      "emojiSearch": "Search emoji…",
      "emojiNoResults": "No emoji found",
      "uploadLevelHint": "Image upload at Lv.1+",
      "previewing": "Previewing…",
      "preview": "Preview"
    },
    "richTextEditor": {
      "orderedList": "Numbered list",
      "linkPrompt": "Enter URL"
    },
    "postEditor": {
      "modeLabel": "Editor:",
      "markdownMode": "Markdown",
      "wysiwygMode": "Visual",
      "wysiwygHint": "Visual editing — content is saved as Markdown, identical to the source mode."
    },
    "imageUpload": {
      "uploadFailed": "Upload failed",
      "uploading": "Uploading…",
      "insertImage": "Insert image"
    },
    "attachmentUpload": {
      "uploadFailed": "Upload failed",
      "uploading": "Uploading…",
      "scanning": "Scanning…",
      "scanFailed": "The attachment did not pass the security scan.",
      "scanTimeout": "The security scan is taking longer than expected. Try again later.",
      "addAttachment": "Add attachment",
      "uploadLevelHint": "File attachments at Lv.1+",
      "pending": "Pending attachments",
      "remove": "Remove"
    },
    "fileInput": {
      "chooseFile": "Choose file"
    },
    "select": {
      "placeholder": "Select…"
    }
  }
} as Record<string, unknown>
