// Generated by scripts/generate-frontend-application-locales.mjs. Edit the full locale catalog, then regenerate.
export default {
  "website": {
    "layout": {
      "brand": "McWeb",
      "home": "Home",
      "about": "About",
      "blog": "Blog",
      "forum": "Forum",
      "store": "Store",
      "enterApp": "Open app →",
      "tagline": "Open-source community & store for Minecraft server owners",
      "siteSection": "Website",
      "appSection": "App",
      "signIn": "Sign in",
      "logoAlt": "Site logo",
      "copyright": "▣ {year} McWeb · Website, community, and store in one place"
    },
    "home": {
      "badge": "Open-source Minecraft server management",
      "heroLine1": "Build a website",
      "heroLine2": "for your",
      "heroLine3": "server",
      "heroDesc": "Forum, store, and accounts work together so players can join the community, follow updates, and manage orders.",
      "enterApp": "Open app center →",
      "learnMore": "Learn more",
      "stat1Value": "3-in-1",
      "stat1Label": "Site · Forum · Store",
      "stat2Value": "Player hub",
      "stat2Label": "Accounts · content · orders",
      "stat3Value": "Customizable",
      "stat3Label": "Pages · themes · navigation",
      "featuresLabel": "Core features",
      "featuresTitle": "All-in-one server owner toolkit",
      "featuresSubtitle": "From attracting players to community ops and monetization — McWeb brings it together.",
      "forumTitle": "Community forum",
      "forumDesc": "Sections, topics, DMs, and moderation — keep players engaged.",
      "storeTitle": "Digital store",
      "storeDesc": "Products, cart, payments, and Minecraft fulfillment in one flow.",
      "identityTitle": "Accounts & security",
      "identityDesc": "Sign-in, email verification, 2FA, and fine-grained permissions for your team.",
      "storeSection": "Store",
      "featuredProducts": "Featured products",
      "allProducts": "All products →",
      "announcements": "News",
      "latestNews": "Latest updates",
      "ctaLabel": "Get started",
      "ctaTitle": "Ready to launch your server website?",
      "ctaDesc": "Open the app center for forum and store — or customize public pages in admin.",
      "registerFree": "Sign up free",
      "viewAnnouncements": "View announcements"
    },
    "articles": {
      "title": "News & announcements",
      "colTitle": "Title",
      "colType": "Type",
      "colPublished": "Published",
      "empty": "No published articles yet.",
      "backToBlog": "Back to blog"
    },
    "pages": {
      "unknownBlock": "This content is temporarily unavailable"
    }
  }
} as Record<string, unknown>
